### ISSUE TITLE
Unraid 6.12 Stable

### ISSUE THREAD

**Issue by ThomasAsh** [stl88083365/unraid-nvidia-vgpu-driver#11]
Hi, have attempted install on 6.12 with latest kernel release but server fails to boot.

Any ideas on a fix?

**Comment by stl88083365** [comment]
There are no error reports for failure to start yet, if you can, upload your logs

**Comment by ThomasAsh** [comment]
Unable to retrieve logs unfortunately, but system would hang just prior to presenting the unraid login info right at end of boot. Boots fine when plugin and associated folders are deleted

**Comment by stl88083365** [comment]
This has nothing to do with the vgpu plugin, you can remove the vgpu plugin first, and then try to reinstall the plugin after unraid 6.12.0 is working properly

**Comment by CIURI86** [comment]
The plugin hangs on install :  /usr/bin/php -q /usr/local/sbin/plugin install /boot/config/plugins/nvidia-vgpu-driver.plg killing the proces resumes booting.

The error on my system with RTX 3050 is nvidia-modeset: ERROR: GPU:0: Error while waiting for GPU progress: 0x0000c67d:0 2:2:0:4040

The nvidia driver loads succesfully , tested with nvidia-smi and the gpu shows till the package installs then it fails with the above error 

[   38.221817] nvidia: loading out-of-tree module taints kernel.
[   38.221826] nvidia: module license 'NVIDIA' taints kernel.
[   38.327688] nvidia: vup_inject_hooks cetbit=0 cudahost=1 vupdevid=0 klogtrace=0
[   38.327705] nvidia: vup_apply_patches vgpusig=1 kunlock=1 qmode=0 merged=1 fbcon=1 sunlock=0
[   38.327718] nvidia: vgpu-kvm-merged build vgpukvm=1 kmalimit=8192
[   38.328455] nvidia-nvlink: Nvlink Core is being initialized, major device number 241
[   38.329971] nvidia 0000:2c:00.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=none:owns=none
[   38.382158] nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  525.105.17  Tue Mar 28 22:18:37 UTC 2023
[   38.383341] [drm] [nvidia-drm] [GPU ID 0x00002c00] Loading driver
[   38.383352] [drm] Initialized nvidia-drm 0.0.0 20160202 for 0000:2c:00.0 on minor 1
[   88.103912] nvidia: vup_hook cudahost=1 flag=1
[   88.692214] nvidia: vup_hook_vupdevid 10de:2507 19da:d630
[   93.748384] nvidia-modeset: ERROR: GPU:0: Error while waiting for GPU progress: 0x0000c67d:0 2:2:0:4040

**Comment by stl88083365** [comment]
Sorry, currently vgpu only supports 10xx and 20xx, 30xx should still not be supported

**Comment by PracticalChip** [comment]
I have a Quadro P2000 and im getting no mdevctl types output.

**Comment by stl88083365** [comment]
Specifically to look at, and what the log file suggests? And did you reboot after installing the driver?

**Comment by Xaero252** [comment]
No release tags match the current kernel version on unraid:
```
# uname -r
6.1.38-Unraid
```

Current release page only has 6.1.36.
