### ISSUE TITLE
Tesla cards

### ISSUE THREAD

**Issue by mikeyo** [stl88083365/unraid-nvidia-vgpu-driver#12]
Is the drive pre-patched for consumer cards? What if I want to use a Tesla P4 / P40 with this driver, will it work?
Also what is the process of assigning a vgpu to a VM/docker, can it be doen via web UI or only via config edits?

**Comment by roofuskit** [comment]
Under the code page 1.png appears to show a Tesla P4 with vgpu drivers working. I would assume that means they have it running.

**Comment by mikeyo** [comment]
Ah yes, seems like it might work then. I just need to know how the vpu is assigned to the VM in UNRAID is it by config edit or can you add a vgpu to a vm in the web ui?

**Comment by s1oz** [comment]
> Ah yes, seems like it might work then. I just need to know how the vpu is assigned to the VM in UNRAID is it by config edit or can you add a vgpu to a vm in the web ui?

Please fill in the following content in the XML and modify the corresponding UUID and PCI.

```
    <hostdev mode='subsystem' type='mdev' managed='no' model='vfio-pci' display='off'>
      <source>
        <address uuid='2b6976dd-8620-49de-8d8d-ae9ba47a50db'/>
      </source>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </hostdev>
```

**Comment by roofuskit** [comment]
> > Ah yes, seems like it might work then. I just need to know how the vpu is assigned to the VM in UNRAID is it by config edit or can you add a vgpu to a vm in the web ui?
> 
> Please fill in the following content in the XML and modify the corresponding UUID and PCI.
> 
> ```
>     <hostdev mode='subsystem' type='mdev' managed='no' model='vfio-pci' display='off'>
>       <source>
>         <address uuid='2b6976dd-8620-49de-8d8d-ae9ba47a50db'/>
>       </source>
>       <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
>     </hostdev>
> ```

I can't seem to get this information to work. I changed the UUID to match one I assigned in the script. I get the following error.

`Execution error

internal error: qemu unexpectedly closed the monitor: qxl_send_events: spice-server bug: guest stopped, ignoring 2023-10-07T20:30:17.814649Z qemu-system-x86_64: -device {"driver":"vfio-pci","id":"hostdev0","sysfsdev":"/sys/bus/mdev/devices/7de667e1-12ef-4d72-a976-197463922e43","display":"off","bus":"pci.4","addr":"0x0"}: vfio 7de667e1-12ef-4d72-a976-197463922e43: error getting device from group 17: Input/output error Verify all devices in group 17 are bound to vfio- or pci-stub and not already in use`

**Comment by roofuskit** [comment]
I found the resolution here https://gitlab.com/polloloco/vgpu-proxmox#vgpu-overrides

Profiles ending in C like the one I originally chose DO NOT work for Windows VMs. It seems that was my issue. i was even able to spoof the card to appear as a Quadro P6000 to avoid having to use the locked down Grid Drivers.

**Comment by roofuskit** [comment]
My next question, if anyone knows, how do I pass through a vgpu to a docker container?

**Comment by stl88083365** [comment]
Q is recommended and not recommended for other

**Comment by phoenixxie0** [comment]
> I found the resolution here https://gitlab.com/polloloco/vgpu-proxmox#vgpu-overrides
> 
> Profiles ending in C like the one I originally chose DO NOT work for Windows VMs. It seems that was my issue. i was even able to spoof the card to appear as a Quadro P6000 to avoid having to use the locked down Grid Drivers.

So how to Tesla P4 on Win?
我也出现了类似问题，提示
internal error: qemu unexpectedly closed the monitor: qxl_send_events: spice-server bug: guest stopped, ignoring 2024-07-24T17:29:37.263930Z qemu-system-x86_64: -device {"driver":"vfio-pci","id":"hostdev0","sysfsdev":"/sys/bus/mdev/devices/9ab318bd-c627-418b-8fd4-8adfec6dacb2","display":"off","bus":"pcie.0","addr":"0x3"}: vfio 9ab318bd-c627-418b-8fd4-8adfec6dacb2: error getting device from group 16: Input/output error Verify all devices in group 16 are bound to vfio- or pci-stub and not already in use
