### ISSUE TITLE
Unraid 6.12.4 installation

### ISSUE THREAD

**Issue by geojoh** [stl88083365/unraid-nvidia-vgpu-driver#13]
I am not sure what I am doing wrong but I cannot make this work properly. I am running Unraid 6.12.4 with a Tesla P4. I tried to install the plg and all i get is an error. I have previously uninstalled the nvidia driver and rebooted. Is this version compatible with unraid 6.12.4 or am I missing some obvious steps? What can I do to make it work? Thank you

plugin: installing: nvidia-vgpu-driver.plg
plugin: downloading: nvidia-vgpu-driver-2023.06.28.txz ... done

+==============================================================================
| Skipping package nvidia-vgpu-driver-2023.06.28 (already installed)
+==============================================================================

-----ERROR - ERROR - ERROR - ERROR - ERROR - ERROR - ERROR - ERROR - ERROR------
------

Can't get latest Nvidia vgpu driver version and found no installed local driver

plugin: run failed: '/bin/bash' returned 1
Executing hook script: gui_search_post_hook.sh
Executing hook script: post_plugin_checks

**Comment by geojoh** [comment]
Looks like there is no release for kernel 6.1.49, so that might explain why it’s not working. Perhaps there is a newer one available that the rep owner could share 😊

**Comment by mikeyo** [comment]
I also have P4. I manually installed driver nvidia-525.125.06-6.1.36-Unraid using installpkg but it still doesnt work 👎
