### ISSUE TITLE
UBU

### ISSUE THREAD

**Issue by mikeyo** [stl88083365/unraid-nvidia-vgpu-driver#14]
What is the UBU in script config? And where do I find it?

UBU="5fd6286d-06ac-4406-8b06-f26511c260d3"

**Comment by stl88083365** [comment]
This is just a variable with no specific meaning

**Comment by mikeyo** [comment]
> This is just a variable with no specific meaning

OK, so we dont have to change it? Just the WIN, NVPCI and MDEVLIST need changing?

## Modify the following variables to suit your environment
WIN="2b6976dd-8620-49de-8d8d-ae9ba47a50db"
UBU="5fd6286d-06ac-4406-8b06-f26511c260d3"
NVPCI="0000:03:00.0"
MDEVLIST="nvidia-65"

**Comment by stl88083365** [comment]
yea
