### ISSUE TITLE
Remove Plugin Update Helper

### ISSUE THREAD

**Issue by ich777** [stl88083365/unraid-nvidia-vgpu-driver#2]
Can you please remove this code block: [Click](https://github.com/stl88083365/unraid-nvidia-vgpu-driver/blob/master/nvidia-vgpu-driver.plg#L206-L209)

This won't work with your plugin and is not necessary.

**Comment by draco1544** [comment]
@ich777 can you support vgpu in your plugin ? Or do a separate plugin ?

**Comment by ich777** [comment]
@draco1544 no, I can't and I won't because.

This violates the Nvidia EULA in more than one ways and I don't want to be associated with it.
That's why I requested the removal of the plugin update helper because it simply does nothing for this plugin.

**Comment by ich777** [comment]
@stl88083365 these lines are also not required: [Click](https://github.com/stl88083365/unraid-nvidia-vgpu-driver/blob/master/nvidia-vgpu-driver.plg#L206-L209)

**Comment by stl88083365** [comment]
Thank you for your guidance

**Comment by stl88083365** [comment]
What needs to be changed, I will actively cooperate, just a hobby, that's all, but I recompiled a driver package that requires the official license of nvidia, can you help make a plug-in for everyone to use?

**Comment by ich777** [comment]
> can you help make a plug-in for everyone to use?

I would be happy too but I can't since this would violate the Nvidia EULA.
For the download of the driver which is needed for vGPU you need to log in to the Nvidia Portal and therefore you have to pay.
A redistribution from these drivers is simply not allowed and would violate the Nvidia EULA.

**Comment by stl88083365** [comment]
Oh. Got it, since I'm not a professional programmer, I don't know anything about that. Sorry.
