### ISSUE TITLE
Does this plugin support GeForce series?

### ISSUE THREAD

**Issue by prprinu** [stl88083365/unraid-nvidia-vgpu-driver#20]
So I installed it but nothing was shown in mdevctl types.
I saw you mentioned in the most recent [post](https://www.lxg2016.com/56120.html) that it should support GF cards. What could be wrong?

![Screenshot 2023-12-24 193935](https://github.com/stl88083365/unraid-nvidia-vgpu-driver/assets/72260150/09f51322-9d4b-45e1-b4a4-1b1a7d37880d)

![Screenshot 2023-12-24 195307](https://github.com/stl88083365/unraid-nvidia-vgpu-driver/assets/72260150/b19216ee-a98c-406f-922d-7ac4e6ac120e)

**Comment by stl88083365** [comment]
Consumer grade 30xx, 40xx is not supported right now.

**Comment by stl88083365** [comment]
Supports up to 2080

**Comment by prprinu** [comment]
Alright. Still appreciate your work. Keep going Big Bro!
