### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by iwantdat** [stl88083365/unraid-nvidia-vgpu-driver#22]
Could you please describe in more detail how to get this installed on unraid 6.12.5?

Do I install the .txz file manually in the plugin section through unraid? If so, what is the best way to do that?

Do I install the script after I install the plugin?

What are the variables I need to add and where in the script do I add them in order to get my gpu to work simultaneously in a vm and in dockers? ---- What are these variables for? (WIN= UBU= NVPCI= MDEVLIST=)

What gpus are supported?

I have the original unraid nvidia driver plugin already installed, do I need to uninstall that first?

Sorry for all of the questions, thanks for any help.

**Comment by stl88083365** [comment]
可以使用插件来安装。

**Comment by iwantdat** [comment]
Thank you for the response.

Would you be able to answer the other questions?
