### ISSUE TITLE
Working with the current version of unraid ?

### ISSUE THREAD

**Issue by draco1544** [stl88083365/unraid-nvidia-vgpu-driver#3]
Hi ! This plugin is working with this version of unraid ? And what are the possibilities with it ?

**Comment by stl88083365** [comment]
unraid 6.12 beta version, not recommended, only suitable for trying

**Comment by stl88083365** [comment]
When the official version is released, I will consider making

**Comment by draco1544** [comment]
> unraid 6.12 beta version, not recommended, only suitable for trying

It's not working with unraid 6.11.5 ?
