### ISSUE TITLE
CUDA版本问题，CUDA 版本是否可以修改？

### ISSUE THREAD

**Issue by phoenixxie0** [stl88083365/unraid-nvidia-vgpu-driver#32]
CUDA版本问题，CUDA 12.2似乎很多东西不支持？目前驱动版本带的CUDA是12.2.然而python的torch似乎不支持这个版本。
安装会默认使用torch+cu121版本，似乎一些其他的程序也对12.2有点奇怪。请问是否有可能自行更换CUDA版本？

**Comment by stl88083365** [comment]
只能通过降级驱动来更改

**Comment by phoenixxie0** [comment]
THX，
