### ISSUE TITLE
Not working on  Unraid 6.11.5

### ISSUE THREAD

**Issue by eltonk** [stl88083365/unraid-nvidia-vgpu-driver#4]
It's not working with Unraid 6.11.5

I always get this error:
`plugin: installing: nvidia-vgpu-driver.plg
Executing hook script: pre_plugin_checks
plugin: downloading: nvidia-vgpu-driver.plg ... done

plugin: downloading: nvidia-vgpu-driver-2022.09.01.txz ... done

+==============================================================================
| Skipping package nvidia-vgpu-driver-2022.09.01 (already installed)
+==============================================================================

-----ERROR - ERROR - ERROR - ERROR - ERROR - ERROR - ERROR - ERROR - ERROR------
---Can't get latest Nvidia vgpu driver version and found no installed local driver---
plugin: run failed: /bin/bash
Executing hook script: post_plugin_checks`

**Comment by DanITman** [comment]
There is no release for this version.  Check out the releases section.  Need to wait for 6.12. This has to do with the kernel version that 6.11.5 uses.  6.12 is in RC2 so it should be pretty close.

**Comment by DanITman** [comment]
There is no release for this version.  Check out the releases section.  Need to wait for 6.12. This has to do with the kernel version that 6.11.5 uses.  6.12 is in RC2 so it should be pretty close.

**Comment by DanITman** [comment]
The releases section has the kernel version that is supported, not the unraid version.

**Comment by stl88083365** [comment]
I am working on a completely new version. It will be finished in the next couple of days

**Comment by stl88083365** [comment]
Now mainly supporting version 6.10.3
