### ISSUE TITLE
a4000可以使用么

### ISSUE THREAD

**Issue by dhlsam** [stl88083365/unraid-nvidia-vgpu-driver#5]
想请问一下a4000可以使用么

**Comment by stl88083365** [comment]
可以的，a4000就是专业卡

**Comment by DanITman** [comment]
I didn't think a4000 was supported by VGPU.  I don't think there is an unlock script that works with Ampere yet.

**Comment by stl88083365** [comment]
Then you need to test it yourself, after all, my environment and hardware is limited, but you can communicate together
