### ISSUE TITLE
more info

### ISSUE THREAD

**Issue by Djwhitelion** [stl88083365/unraid-nvidia-vgpu-driver#7]
Hi.

I wish there was any informatin given on where to find info to add to the script.
where to find what needs to be replaced here:
## Modify the following variables to suit your environment
WIN="2b6976dd-8620-49de-8d8d-ae9ba47a50db"
UBU="5fd6286d-06ac-4406-8b06-f26511c260d3"
NVPCI="0000:03:00.0"
MDEVLIST="nvidia-65"

i think i found win amd mvpci. but what is UBU and MDEVLIST and how to get that?

**Comment by stl88083365** [comment]
First load the driver using nvidia-modprobe, after using 
LD_PRELOAD=/usr/local/lib/libvgpu_unlock_rs.so nvidia-vgpud 
LD_PRELOAD=/usr/local/lib/libvgpu_unlock_rs.so nvidia-vgpu-mgr
command to load the vgpu service, and then you can use the mdevctl types command to get the relevant parameters.
WIN and UBU are later generated using the uuidgen command.

**Comment by Djwhitelion** [comment]
Hi. Thank you for your prompt reply. 
I'm pretty new to the unRAID space. 
So I'm figuring out things as i go.
I'm betting i haven't installed the plugin correct on the server.
So do I download the content and add it in the plugin folder on the flash? Tried installing plugin via link. But getting error . plugin: unraid-nvidia-vgpu-driver is not a plg file.
Sorry for being such a nuub

**Comment by stl88083365** [comment]
Add 
 https://raw.githubusercontent.com/stl88083365/unraid-nvidia-vgpu-driver/master/nvidia-vgpu-driver.plg to the unraid plugin installation, it will automatically install this plugin

**Comment by Djwhitelion** [comment]
Oh. My 1060 is not supported. 
Oh well. Thank you so much for all your help
![SmartSelect_20230604_202149_Chrome](https://github.com/stl88083365/unraid-nvidia-vgpu-driver/assets/128393605/c9384249-ea4c-492b-85d2-10b8e665fe39)

**Comment by stl88083365** [comment]
There are too many graphics card ids needed, I don't have that much hardware environment for testing, actually just modify the vgpuConfig.xml file to do it

**Comment by roofuskit** [comment]
Is there somewhere we still need to contribute to in order to get the full drivers? Because I do not see that this actually downloads any drivers, just this plugin and a user interface for editing some files. The actual nvidia drivers and vgpu utilities do not seem to download.

**Comment by roofuskit** [comment]
I am running a Tesla P4. I have the latest version of the driver installed and everything seems to be working. I show my card under nvidia-smi. I see my GPU under "nvidia-smi vgpu" but when I start my VM it takes over the whole card. 

I have the UUID from the VM input into the script and have it running on on the start of the array.

Are there instructions for configuring that are not shown under the readme?
